name: sample_full
concurrency: 3
stop_on_fail: true
tasks:
- name: download
  depends_on: []
  run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/EbookFoundation/free-programming-books/master/books/free-programming-books-langs.md" -OutFile "file.txt"
  retries: 2
  timeout: 60
  backend: local
  cache_key: null
  continue_on_fail: null
- name: count
  depends_on:
  - download
  run: (Get-Content file.txt).Length
  retries: null
  timeout: null
  backend: local
  cache_key: null
  continue_on_fail: null
- name: echo
  depends_on:
  - count
  run: Write-Output "The file length was {{count.output}}"
  retries: null
  timeout: null
  backend: local
  cache_key: null
  continue_on_fail: null
